### PR TITLE
Ignore keys with empty, null, [] or {} values when -n is specified

### PR DESCRIPTION
**Pull request by patrick-yingxi-pan**
Suppose you are processing a directory recursively, then the following command
will omit the "subdir" field altogether and returns "{}" if the sub directory
is empty:

jo -n subdir=$(cd subdir && ls | jo -n -a)

### CODE REVIEW

**Comment by jpmens** [comment]
Thanks for your contribution, but I'm going to need lots of help understanding what this is for. Judging by the included tests, I _think_ this alters the default behavior of

```console
$ echo | jo -n -a
[]
```

to output not an empty array `[]` but rather an empty string.

What general purpose would this be used for?

**Comment by patrick-yingxi-pan** [comment]
Previously, the `-n` option was only defined for object mode, meaning omitting field with empty value. This patch introduces a meaningful use of the option for array mode as well. That is, to omit empty array altogether and output an empty string.

The design is to facilitate the processing of recursive structures. Let's say we want to describe the contents of a directory in JSON, and the expected JSON format is 

```
{
    name: dirA,
    contents: [
        {
            name: subDirB,
            contents: []
        }, {
            name: subDirC,
            contents: []
        }
    ]
}
``` 

We can see a clear recursive pattern in generating the `contents` array, and the recursion would be something like:

```
function print_dir
{
    local dir_name=$1
    jo name=$dir_name contents=:<(cd $dir_name && print_contents | jo -a)
}

function print_contents
{
    for subdir in *; do
        print_dir $subdir
    done
}
```

The problem is: how can we omit the `contents` field altogether if its values is `[]`?

Of course, we can call `jo` in `print_dir` with or without the `contents` field, depending on whether the directory is empty. But that clearly makes the recursion complex and induces duplication of code.

My proposed solution in this patch is to make `jo -a` return empty string when `-n` option is enabled. Thus the `contents` field, due to receiving an empty value, can be omitted by enabling `-n` option in the parent command as well.

But wait! Upon further thinking in responding to your question, I suspect we need a new `omit-empty-object` option instead of abusing the existing `-n` option. Because "omitting empty field" isn't quite similar to "omitting empty array" from the design's perspective. When `omit-empty-object` option is enabled:

- `jo` returns empty string for `{}`
- `jo -a` returns empty string for `[]`

What do you think?

**Comment by gromgit** [comment]
I think it would be simpler, and arguably more correct, to distinguish between a datum's "emptiness" and its textual representation.

Off the top of my head, I can think of three JSON values that could be considered "empty":
* the zero-length string `""`
* the empty object `{}`
* the empty array `[]`

Currently, only the first is treated as such by `jo`, but I think all three should be interpreted the same way for the purpose of object key assignment, so:
```sh
jo -n content=       # => {}
jo -n content="{}"   # => {}
jo -n content="[]"   # => {}
```

And I think `jo` should _always_ return an object or array, except in error conditions.

**Comment by jpmens** [comment]
I also think `jo` should always return an object or an array; returning an empty string doesn't _seem_ right to me.

**Comment by patrick-yingxi-pan** [comment]
How about a `-N` option to make `jo` return empty strings for `{}` or `[]`? The original `-n` option can be kept unchanged.

```
jo content=            # => { "content": null }
jo -n content=       # => {}
jo -n -N content=  # =>
```

**Comment by patrick-yingxi-pan** [comment]
> I also think `jo` should always return an object or an array; returning an empty string doesn't _seem_ right to me.

But how can we solve the above mentioned problem? The following workaround doesn't look very good to me:

```
if [[ list_a_is_empty && list_b_is_empty ]]; then
    jo name=dog
elif [[ list_a_is_empty ]]; then
    jo name=dog list_b=:<(generate_list_b)
else
    jo name=dog list_a=:<(generate_list_a) list_b=:<(generate_list_b)
fi
```

If there are many common fields like `name`, the user has to employ language features to avoid code duplication.

**Comment by patrick-yingxi-pan** [comment]
> I think it would be simpler, and arguably more correct, to distinguish between a datum's "emptiness" and its textual representation.
> 
> Off the top of my head, I can think of three JSON values that could be considered "empty":
> 
> * the empty value (as opposed to the 2-character literal string `""`)
> * the empty object `{}`
> * the empty array `[]`
> 
> Currently, only the first is treated as such by `jo`, but I think all three should be interpreted the same way for the purpose of object key assignment, so:
> 
> ```shell
> jo -n content=       # => {}
> jo -n content="{}"   # => {}, now {"content":{}}
> jo -n content="[]"   # => {}, now {"content":[]}
> ```
> 
> And I think `jo` should _always_ return an object or array, except in error conditions.

Hmm, this proposal effectively treats `null`, `{}` and `[]` identical. It might be a good idea as well.

**Comment by patrick-yingxi-pan** [comment]
Perhaps we can agree on this design:

1. Keep the `-n` behavior unchanged. That is, `jo` always returns an object or an array.
2. Add a new `-N` option, meaning treating more values as empty in addition to that of `-n`, including `null`, `{}` and `[]`. Note that `-n` only ignores fields like `field=`, but not `field=null`, `field={}` or `field=[]`.
3. `-N` and `-n -N` are equivalent. That is, `field=`, `field=null`, `field={}` and `field=[]` will all be ignored.

**Comment by gromgit** [comment]
> > I also think `jo` should always return an object or an array; returning an empty string doesn't _seem_ right to me.
> 
> But how can we solve the above mentioned problem? The following workaround doesn't look very good to me:
> 
> ```
> if [[ list_a_is_empty && list_b_is_empty ]]; then
>     jo name=dog
> elif [[ list_a_is_empty ]]; then
>     jo name=dog list_b=:<(generate_list_b)
> else
>     jo name=dog list_a=:<(generate_list_a) list_b=:<(generate_list_b)
> fi
> ```
> 
> If there are many common fields like `name`, the user has to employ language features to avoid code duplication.

As long as all your `generate_list_X` print `[]` for empty lists, then in my proposal, if `a` is empty but `b` isn't:
```
jo -n name=dog list_a=:<(generate_list_a) list_b=:<(generate_list_b)
# => {"name":"dog","list_b":["fenton","fenton!","FENTON!","FENTONNNNN!"]}
```

**Comment by patrick-yingxi-pan** [comment]
> > > I also think `jo` should always return an object or an array; returning an empty string doesn't _seem_ right to me.
> > 
> > 
> > But how can we solve the above mentioned problem? The following workaround doesn't look very good to me:
> > ```
> > if [[ list_a_is_empty && list_b_is_empty ]]; then
> >     jo name=dog
> > elif [[ list_a_is_empty ]]; then
> >     jo name=dog list_b=:<(generate_list_b)
> > else
> >     jo name=dog list_a=:<(generate_list_a) list_b=:<(generate_list_b)
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If there are many common fields like `name`, the user has to employ language features to avoid code duplication.
> 
> As long as all your `generate_list_X` print `[]` for empty lists, then in my proposal:
> 
> ```
> jo -n name=dog list_a=:<(echo "[]") list_b=:<(richmond_park_incident)
> # => {"name":"dog","list_b":["fenton","fenton!","FENTON!","FENTONNNNN!"]}
> ```

Yep. My latest proposal of `-N` effectively does this, but with an entirely new option to be backward compatible. What do you think?

**Comment by jpmens** [comment]
I agree with you, Adrian.

**Comment by patrick-yingxi-pan** [comment]
@gromgit @jpmens So just make the existing `-n` option ignore `field=`, `field=null`, `field={}` and `field=[]`? Is that the design we agree upon?

**Comment by gromgit** [comment]
Yeah, I think that's the way forward.

**Comment by patrick-yingxi-pan** [comment]
OK. I will tune this patch accordingly. Thanks guys!

**Comment by patrick-yingxi-pan** [comment]
@jpmens @gromgit Diff updated. Please take a look.

**Comment by gromgit** [comment]
I'm somewhat uncomfortable with your current implementation, as it means that JSON output that was generated and "fixed" at lower levels can suddenly be collapsed into nothing by a single `-n` at the top level. In particular:
```
jo -n key="$(jo foo=)"
```
really shouldn't be collapsed into an empty object, as `-n` is explicitly applied at only the `key` level.

(That said, I can see a use case for "recursively elide all empty keys", for which a separate `-N` option makes sense, to avoid surprising the user.)

However, I'm _very_ uncomfortable with the changes you've made to `json.c`. In my mind, parsing JSON should be an entirely separate activity from _editing_ JSON (which is basically the point of this PR), and pushing skip-null logic down into the parsing level increases the probability of unexpected side-effects as further changes are added in the long term, thus reducing overall maintainability. Ideally, `json.c` should only ever be edited to fix parsing bugs, as the JSON spec itself is frozen.

In fact, I tried implementing this PR independently while the original discussion was still going on, and the "skip-null" logic is _much_ easier to implement after the parsing is done:
```diff --git a/jo.c b/jo.c
index f7c2cd9..57837b2 100644
--- a/jo.c
+++ b/jo.c
@@ -211,6 +211,21 @@ JsonNode *jo_mknumber(char *str, JsonTag type) {
        }
 }
 
+bool jo_isempty(JsonNode *obj) {
+       switch (obj->tag) {
+               case JSON_NULL:
+                       return true;
+                       break;
+               case JSON_ARRAY:
+               case JSON_OBJECT:
+                       return obj->children.head == (JsonNode *)NULL && obj->children.tail == (JsonNode *)NULL;
+                       break;
+               default:
+                       return false;
+                       break;
+       }
+}
+
 /*
  * Attempt to "sniff" the type of data in `str' and return
  * a JsonNode of the correct JSON type.
@@ -293,7 +308,7 @@ JsonNode *vnode(char *str, int flags)
                                j = json_mkstring(content);
                        }
                        free(content);
-                       return (j);
+                       return (flags & FLAG_SKIPNULLS) && jo_isempty(j) ? (JsonNode *)NULL : j;
                }
        }
 
@@ -310,7 +325,7 @@ JsonNode *vnode(char *str, int flags)
                        obj = json_mkstring(str);
                }
 
-               return (obj);
+               return (flags & FLAG_SKIPNULLS) && jo_isempty(obj) ? (JsonNode *)NULL : obj;
        }
 
        return jo_mkstring(str, type);
```
That's everything needed to implement the stated goal of this PR. If you want to extend this to support recursive "trimming", I think it should be quite a bit easier to accomplish at this level too.

**Comment by gromgit** [comment]
Apologies, I spoke too soon. My own patch isn't completely correct:
```
$ ./jo -n geo[]= geo[]={} geo[]=[]
{"geo":[]}   # => should be {}
```

**Comment by patrick-yingxi-pan** [comment]
> Apologies, I spoke too soon. My own patch isn't completely correct:
> 
> ```
> $ ./jo -n geo[]= geo[]={} geo[]=[]
> {"geo":[]}   # => should be {}
> ```
> 
> UPDATE: Well, it _is_ correct with respect to extending the "don't add empties" behavior to different kinds of "empty", but I wonder if, in the above scenario, the `geo` node should be created at all.

Don't worry. My patch doesn't work either:
```
$ ./jo -n geo[]=null geo[]=[] geo[]={} geo[]=
{"geo":[]}
$ ./jo -n geo[]=null
{"geo":[]}
```

This, as well as other concerns on `-N` and `json.c`, should be fixed, and I will do it anytime soon.

**Comment by jpmens** [comment]
Closing as stale.

**Pull request closed without merging**
