### PR TITLE
Add bash completion

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by jpmens** [comment]
Thank you for your contribution. I'm not a big user of bash completion (other than files/directories :), so can you please explain a bit what this actually does? I fail to see what could be completed ...

I'd also appreciate feedback from other people whether they consider this useful.

**Comment by scop** [comment]
It completes:
- available options when entering `-<tab>`
- filenames after `foo=%` and `foo=@`
...and _prevents_ further completions if `-h`, `-v`, or `-V` has been given

**Comment by jpmens** [comment]
Merged, thank you.

**Comment by jpmens** [comment]
@scop any idea why the Linux builds are failing? I can't reproduce on OS/X ...

https://travis-ci.org/jpmens/jo/builds/606789826

I see from the build output that the installer is trying to write to

```
/usr/bin/install: cannot create regular file '/usr/share/bash-completion/completions/jo.bash': Permission denied
```

I assume that's due to a missing automake variable?

**Comment by scop** [comment]
It's because `distcheck` apparently tries to do a staged install just by configuring to a prefix, and the bash-completion completions dir is not subject to that prefix when it's found in the bash completion pkgconfig file. OS X builds are not affected because the fallback /etc/bash_completion.d dir _is_ subject to the prefix.

That kind of usage seems broken to me, DESTDIR is the proper way to do staged installs. Curiously, the autotools generated distcheck appears to try both the prefix and the DESTDIR approach. I'll see if I can find a way to not try the prefix one at all.

**Comment by scop** [comment]
Hmph, looks like there is no way to do that. Neither do I want to change the stuff we support in bash-completion to be subject to --prefix, because if for example bash-completion is installed in /some/prefix, completions for it should be installed there no matter what for example a jo builder sets their --prefix to when building jo, otherwise they won't work/be used.

So unfortunately this means all projects using our documented and suggested autotools helpers have a broken distcheck :/ I suggest just not doing it then, i.e. reverting #101.

**Comment by jpmens** [comment]
@scop thank you very much; done as suggested.

**Pull request merged**
