### PR TITLE
Fix length bug in slurp_file.

### PR DESCRIPTION
**Pull request by stevecheckoway**
Under Windows, \r\n is converted to \n in text mode which makes the length of
the returned string different from the file size. A similar issue happens when
fold_newlines is true; however, this isn't currently used so the bug isn't
triggered.

### CODE REVIEW

**Comment by jpmens** [comment]
Glancing at this: are you skipping over newlines in the target string anyway? That differs from the original intention; keep them (except the last).

**Comment by jpmens** [comment]
By which I mean, irrespective of fold_newlines?

**Comment by stevecheckoway** [comment]
The original version kept all newlines unless fold_newlines was true in which case it skipped all of them. I believe my version maintains that logic.

**Comment by jpmens** [comment]
Now I see it. It's been a long day for me, and I'm not in my usual habitat.

Merging, thank you.

**Pull request merged**
